import AppKit
import SwiftUI

/// Читает системный буфер обмена и ведёт историю.
///
/// Уведомлений об изменении пастборда в macOS нет — единственный способ узнать
/// о копировании — периодически сравнивать `changeCount`. Так работают все
/// менеджеры буфера.
@MainActor
final class ClipboardService: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    private let pollInterval: TimeInterval = 0.45
    /// Пока человек не за компьютером, буфер меняться почти не может:
    /// копирует всегда он сам. Исключение — универсальный буфер с телефона,
    /// но лишние две секунды задержки там ничего не решают.
    private let awayPollInterval: TimeInterval = 2.5
    private let awayAfter: TimeInterval = 30
    private var isAway = false
    private let settings: SettingsStore

    init(settings: SettingsStore) {
        self.settings = settings
        if settings.persistClipboard {
            items = ClipboardStore.load()
        }
    }

    /// Служебные типы, которыми приложения помечают содержимое, не предназначенное
    /// для истории. Первый из них ставят менеджеры паролей — без этой проверки
    /// история за день соберёт все скопированные пароли в открытом виде.
    /// Соглашение описано на nspasteboard.org.
    /// Пришло содержимое с другого устройства.
    var onRemoteContent: ((ClipboardItem) -> Void)?

    /// Метка универсального буфера: содержимое скопировано на другом
    /// устройстве и доехало по Handoff.
    static let remoteMarker = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")

    private let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type"),
    ]

    func start() {
        schedule()
    }

    private func schedule() {
        stop()
        let interval = isAway ? awayPollInterval : pollInterval
        let timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Прочитать буфер прямо сейчас, не дожидаясь следующего опроса.
    /// Нужно при открытии истории: человек мог скопировать что-то за
    /// мгновение до этого.
    func pollNow() {
        adaptInterval()
        poll()
    }

    /// Реже опрашивать, когда за компьютером никого нет.
    private func adaptInterval() {
        let away = IdleWatcher.secondsSinceLastInput() >= awayAfter
        guard away != isAway else { return }
        isAway = away
        schedule()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Добавить элемент со стороны — например, только что сделанный снимок
    /// экрана: файл на диске полезен, но чаще его хотят просто вставить.
    func add(_ item: ClipboardItem) {
        if let first = items.first, first.hasSameContent(as: item) { return }

        if item.fromOtherDevice { onRemoteContent?(item) }

        items.insert(item, at: 0)
        if items.count > settings.clipboardLimit {
            items.removeLast(items.count - settings.clipboardLimit)
        }
        if settings.persistClipboard {
            ClipboardStore.save(items, limit: settings.clipboardLimit)
        }

        // История ограничена лимитом и живёт для вставки; журнал хранит всё.
        if settings.archiveEverything {
            ClipboardArchive.append(item)
        }
    }

    /// Что было в истории до последней очистки. Держим, пока не закроют
    /// окно буфера: «очистить» — единственное необратимое действие здесь,
    /// и промахнуться по нему легко.
    @Published private(set) var lastCleared: [ClipboardItem]?

    func clear() {
        let removed = items.filter { !$0.isPinned }
        guard !removed.isEmpty else { return }

        lastCleared = items
        // Закреплённое переживает очистку: его закрепили именно для этого.
        items.removeAll { !$0.isPinned }
        persist()
    }

    func undoClear() {
        guard let lastCleared else { return }
        items = lastCleared
        self.lastCleared = nil
        persist()
    }

    func forgetUndo() {
        lastCleared = nil
    }

    /// Пипетка: взять цвет с экрана и положить в буфер.
    ///
    /// Системный `NSColorSampler` рисует лупу сам и разрешений не требует —
    /// это не снимок экрана, а выбор одной точки, и делает его система.
    func pickColor(completion: (@MainActor () -> Void)? = nil) {
        NSColorSampler().show { color in
            MainActor.assumeIsolated {
                guard let color else { return }
                let item = ClipboardItem(
                    kind: .color(color),
                    date: Date(),
                    sourceName: t("ui.f30b8a19", "Пипетка")
                )
                self.items.insert(item, at: 0)
                self.sortPinnedFirst()
                self.persist()
                self.copyToPasteboard(item)
                completion?()
            }
        }
    }

    /// Выполнить действие, предложенное для элемента.
    func perform(_ action: ClipboardItem.Action) {
        switch action {
        case .openLink(let url):
            NSWorkspace.shared.open(url)

        case .revealFiles(let urls):
            NSWorkspace.shared.activateFileViewerSelecting(urls)

        case .colorAsRGB(let color):
            guard let rgb = color.usingColorSpace(.sRGB) else { return }
            let text = String(
                format: "rgb(%d, %d, %d)",
                Int(round(rgb.redComponent * 255)),
                Int(round(rgb.greenComponent * 255)),
                Int(round(rgb.blueComponent * 255))
            )
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(text, forType: .string)
            lastChangeCount = NSPasteboard.general.changeCount

        case .formatJSON(let text):
            guard let pretty = Self.prettyJSON(text) else { return }
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(pretty, forType: .string)
            lastChangeCount = NSPasteboard.general.changeCount

        case .pasteCode(let code):
            NSPasteboard.general.clearContents()
            NSPasteboard.general.setString(code, forType: .string)
            lastChangeCount = NSPasteboard.general.changeCount
            Paster.pasteIntoFrontmostApp()
        }
    }

    /// Чистая функция, ничего от объекта ей не нужно.
    nonisolated static func prettyJSON(_ text: String) -> String? {
        guard let data = text.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data),
              let pretty = try? JSONSerialization.data(
                  withJSONObject: object,
                  options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
              )
        else { return nil }
        return String(decoding: pretty, as: UTF8.self)
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        sortPinnedFirst()
        persist()
    }

    private func sortPinnedFirst() {
        items.sort { lhs, rhs in
            lhs.isPinned != rhs.isPinned ? lhs.isPinned : lhs.date > rhs.date
        }
    }

    private func persist() {
        guard settings.persistClipboard else { return }
        ClipboardStore.save(items, limit: settings.clipboardLimit)
    }

    /// Кладёт элемент обратно в системный буфер.
    ///
    /// `plain` — вставить без оформления: срезать шрифты, цвета и размеры,
    /// оставив голый текст. Это то, ради чего люди держат в голове
    /// ⌥⇧⌘V — а половина приложений её и не понимает.
    func copyToPasteboard(_ item: ClipboardItem, plain: Bool = true) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        switch item.kind {
        case .text(let value):
            if !plain, let rich = item.richText {
                pasteboard.setData(rich, forType: .rtf)
            }
            pasteboard.setString(value, forType: .string)
        case .link(let url):
            pasteboard.setString(url.absoluteString, forType: .string)
        case .image(let image):
            pasteboard.writeObjects([image])
        case .files(let urls):
            Self.write(files: urls, to: pasteboard)
        case .color(let color):
            pasteboard.setString(color.hexString, forType: .string)
        }

        // Собственная запись не должна вернуться в историю дублем.
        lastChangeCount = pasteboard.changeCount
    }

    /// Кладёт только что сделанный снимок в системный буфер.
    ///
    /// macOS умеет снимать сразу в буфер (⌃⌘⇧4), но помнить эту комбинацию
    /// приходится заранее — а решение «нужен файл или вставить» принимается
    /// уже после снимка. Поэтому снимок ложится и на диск, и в буфер.
    func copyScreenshot(_ url: URL) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        Self.write(files: [url], to: pasteboard)
        lastChangeCount = pasteboard.changeCount
    }

    /// Файл кладётся в буфер двумя представлениями сразу: ссылкой и, если это
    /// картинка, самим изображением. Приложение возьмёт то, что понимает:
    /// почта приложит файл, редактор вставит картинку. Одним типом всегда
    /// проигрываешь половине приложений.
    static func write(files urls: [URL], to pasteboard: NSPasteboard) {
        let item = NSPasteboardItem()
        var wroteAnything = false

        if urls.count == 1, let url = urls.first {
            item.setString(url.absoluteString, forType: .fileURL)
            wroteAnything = true

            // Читаем с диска отображением в память: снимок Retina-экрана
            // весит мегабайты, и копировать их в кучу незачем.
            if let data = try? Data(contentsOf: url, options: .mappedIfSafe),
               let type = imageType(of: url) {
                item.setData(data, forType: type)
            }
        }

        if wroteAnything {
            pasteboard.writeObjects([item])
        } else {
            pasteboard.writeObjects(urls as [NSURL])
        }
    }

    /// Тип пастборда по расширению файла. Перекодировать ничего не нужно —
    /// данные кладутся как есть, лишь бы получатель знал, что это.
    static func imageType(of url: URL) -> NSPasteboard.PasteboardType? {
        switch url.pathExtension.lowercased() {
        case "png": return .png
        case "tiff", "tif": return .tiff
        case "jpg", "jpeg": return NSPasteboard.PasteboardType("public.jpeg")
        case "heic": return NSPasteboard.PasteboardType("public.heic")
        case "pdf": return .pdf
        default: return nil
        }
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else {
            adaptInterval()
            return
        }
        lastChangeCount = pasteboard.changeCount

        guard let types = pasteboard.types else { return }
        guard !types.contains(where: ignoredTypes.contains) else { return }

        // Из некоторых приложений историю вести не нужно вовсе: метку
        // `org.nspasteboard` ставят не все менеджеры паролей и не всякий
        // банк-клиент.
        let source = NSWorkspace.shared.frontmostApplication?.localizedName
        if let source {
            settings.rememberClipboardSource(source)
            guard !settings.clipboardExcludedApps.contains(source) else { return }
        }

        guard let kind = readKind(from: pasteboard) else { return }

        var item = ClipboardItem(
            kind: kind,
            date: Date(),
            sourceName: source
        )
        // Универсальный буфер помечает содержимое, приехавшее с другого
        // устройства. Кроме этой метки узнать о нём неоткуда.
        item.fromOtherDevice = types.contains(Self.remoteMarker)
        // Оформление забираем сразу: второй раз в системном буфере его уже
        // не будет — там окажется следующее скопированное.
        if case .text = kind {
            item.richText = pasteboard.data(forType: .rtf)
        }

        if let first = items.first, first.hasSameContent(as: item) { return }

        if ProcessInfo.processInfo.environment["AURA_DEBUG"] == "1" {
            NSLog("Aura: поймано в буфере [%@] %@", item.symbol, String(item.title.prefix(60)))
        }

        items.insert(item, at: 0)
        if items.count > settings.clipboardLimit {
            items.removeLast(items.count - settings.clipboardLimit)
        }

        if settings.persistClipboard {
            ClipboardStore.save(items, limit: settings.clipboardLimit)
        }

        // История ограничена лимитом и живёт для вставки; журнал хранит всё.
        if settings.archiveEverything {
            ClipboardArchive.append(item)
        }
    }

    /// Чинит текст, который положили в буфер как UTF-8, а система отдала
    /// разобранным в однобайтовой кодировке: «привет» превращается в «–њ—А–Є...».
    /// Такое присылают консольные утилиты и старые приложения.
    nonisolated static func repairEncoding(_ text: String) -> String {
        // Признак поломки — символы, которых в осмысленном тексте почти не бывает
        // подряд: они получаются из первых байтов кириллических пар UTF-8.
        let markers: Set<Character> = ["–", "—", "Ð", "Ñ", "Ã", "‚", "†", "¬"]
        guard text.contains(where: markers.contains) else { return text }

        // Байты UTF-8 могли быть разобраны как любая однобайтовая кодировка —
        // какая именно, зависит от системы отправителя, поэтому перебираем.
        let candidates: [String.Encoding] = [
            .init(rawValue: CFStringConvertEncodingToNSStringEncoding(
                CFStringEncoding(CFStringEncodings.macCyrillic.rawValue)
            )),
            .macOSRoman,
            .init(rawValue: CFStringConvertEncodingToNSStringEncoding(
                CFStringEncoding(CFStringEncodings.windowsCyrillic.rawValue)
            )),
            .isoLatin1,
        ]

        for encoding in candidates {
            guard let data = text.data(using: encoding),
                  let repaired = String(data: data, encoding: .utf8),
                  !repaired.isEmpty,
                  repaired.contains(where: { $0.isLetter })
            else { continue }
            return repaired
        }

        return text
    }

    /// В историю попадает уменьшенная копия: полноразмерные снимки экрана
    /// в сотне карточек — это сотни мегабайт памяти.
    private static func downscaled(_ image: NSImage, maxSide: CGFloat = 320) -> NSImage {
        let size = image.size
        guard size.width > maxSide || size.height > maxSide, size.width > 0, size.height > 0 else {
            return image
        }
        let scale = maxSide / max(size.width, size.height)
        let target = CGSize(width: size.width * scale, height: size.height * scale)

        let result = NSImage(size: target)
        result.lockFocus()
        NSGraphicsContext.current?.imageInterpolation = .medium
        image.draw(in: CGRect(origin: .zero, size: target))
        result.unlockFocus()
        return result
    }

    private func readKind(from pasteboard: NSPasteboard) -> ClipboardItem.Kind? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            return .files(urls)
        }

        if let image = NSImage(pasteboard: pasteboard) {
            return .image(Self.downscaled(image))
        }

        guard let string = pasteboard.string(forType: .string), !string.isEmpty else {
            return nil
        }

        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)

        if let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto"].contains(scheme) {
            return .link(url)
        }

        if let color = NSColor(hex: trimmed) {
            return .color(color)
        }

        return .text(Self.repairEncoding(string))
    }
}

extension NSColor {
    /// Разбирает `#RGB`, `#RRGGBB` и `#RRGGBBAA`.
    convenience init?(hex: String) {
        var value = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        guard value.hasPrefix("#") else { return nil }
        value.removeFirst()

        if value.count == 3 {
            value = value.map { "\($0)\($0)" }.joined()
        }
        guard value.count == 6 || value.count == 8,
              let number = UInt64(value, radix: 16) else { return nil }

        let hasAlpha = value.count == 8
        let shift = hasAlpha ? 8 : 0
        let red = CGFloat((number >> (16 + shift)) & 0xFF) / 255
        let green = CGFloat((number >> (8 + shift)) & 0xFF) / 255
        let blue = CGFloat((number >> shift) & 0xFF) / 255
        let alpha = hasAlpha ? CGFloat(number & 0xFF) / 255 : 1

        self.init(srgbRed: red, green: green, blue: blue, alpha: alpha)
    }
}
