import AppKit
import SwiftUI

/// Читает системный буфер обмена и ведёт историю.
///
/// Уведомлений об изменении пастборда в macOS нет — единственный способ узнать
/// о копировании — периодически сравнивать `changeCount`. Так работают все
/// менеджеры буфера.
@MainActor
final class ClipboardService: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    private let pollInterval: TimeInterval = 0.45
    private let settings: SettingsStore

    init(settings: SettingsStore) {
        self.settings = settings
        if settings.persistClipboard {
            items = ClipboardStore.load()
        }
    }

    /// Служебные типы, которыми приложения помечают содержимое, не предназначенное
    /// для истории. Первый из них ставят менеджеры паролей — без этой проверки
    /// история за день соберёт все скопированные пароли в открытом виде.
    /// Соглашение описано на nspasteboard.org.
    private let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type"),
    ]

    func start() {
        stop()
        let timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Добавить элемент со стороны — например, только что сделанный снимок
    /// экрана: файл на диске полезен, но чаще его хотят просто вставить.
    func add(_ item: ClipboardItem) {
        if let first = items.first, first.hasSameContent(as: item) { return }

        items.insert(item, at: 0)
        if items.count > settings.clipboardLimit {
            items.removeLast(items.count - settings.clipboardLimit)
        }
        if settings.persistClipboard {
            ClipboardStore.save(items, limit: settings.clipboardLimit)
        }

        // История ограничена лимитом и живёт для вставки; журнал хранит всё.
        if settings.archiveEverything {
            ClipboardArchive.append(item)
        }
    }

    /// Что было в истории до последней очистки. Держим, пока не закроют
    /// окно буфера: «очистить» — единственное необратимое действие здесь,
    /// и промахнуться по нему легко.
    @Published private(set) var lastCleared: [ClipboardItem]?

    func clear() {
        let removed = items.filter { !$0.isPinned }
        guard !removed.isEmpty else { return }

        lastCleared = items
        // Закреплённое переживает очистку: его закрепили именно для этого.
        items.removeAll { !$0.isPinned }
        persist()
    }

    func undoClear() {
        guard let lastCleared else { return }
        items = lastCleared
        self.lastCleared = nil
        persist()
    }

    func forgetUndo() {
        lastCleared = nil
    }

    /// Пипетка: взять цвет с экрана и положить в буфер.
    ///
    /// Системный `NSColorSampler` рисует лупу сам и разрешений не требует —
    /// это не снимок экрана, а выбор одной точки, и делает его система.
    func pickColor(completion: (@MainActor () -> Void)? = nil) {
        NSColorSampler().show { color in
            MainActor.assumeIsolated {
                guard let color else { return }
                let item = ClipboardItem(
                    kind: .color(color),
                    date: Date(),
                    sourceName: t("ui.f30b8a19", "Пипетка")
                )
                self.items.insert(item, at: 0)
                self.sortPinnedFirst()
                self.persist()
                self.copyToPasteboard(item)
                completion?()
            }
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        sortPinnedFirst()
        persist()
    }

    private func sortPinnedFirst() {
        items.sort { lhs, rhs in
            lhs.isPinned != rhs.isPinned ? lhs.isPinned : lhs.date > rhs.date
        }
    }

    private func persist() {
        guard settings.persistClipboard else { return }
        ClipboardStore.save(items, limit: settings.clipboardLimit)
    }

    /// Кладёт элемент обратно в системный буфер.
    ///
    /// `plain` — вставить без оформления: срезать шрифты, цвета и размеры,
    /// оставив голый текст. Это то, ради чего люди держат в голове
    /// ⌥⇧⌘V — а половина приложений её и не понимает.
    func copyToPasteboard(_ item: ClipboardItem, plain: Bool = true) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        switch item.kind {
        case .text(let value):
            if !plain, let rich = item.richText {
                pasteboard.setData(rich, forType: .rtf)
            }
            pasteboard.setString(value, forType: .string)
        case .link(let url):
            pasteboard.setString(url.absoluteString, forType: .string)
        case .image(let image):
            pasteboard.writeObjects([image])
        case .files(let urls):
            pasteboard.writeObjects(urls as [NSURL])
        case .color(let color):
            pasteboard.setString(color.hexString, forType: .string)
        }

        // Собственная запись не должна вернуться в историю дублем.
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard let types = pasteboard.types else { return }
        guard !types.contains(where: ignoredTypes.contains) else { return }

        guard let kind = readKind(from: pasteboard) else { return }

        var item = ClipboardItem(
            kind: kind,
            date: Date(),
            sourceName: NSWorkspace.shared.frontmostApplication?.localizedName
        )
        // Оформление забираем сразу: второй раз в системном буфере его уже
        // не будет — там окажется следующее скопированное.
        if case .text = kind {
            item.richText = pasteboard.data(forType: .rtf)
        }

        if let first = items.first, first.hasSameContent(as: item) { return }

        if ProcessInfo.processInfo.environment["AURA_DEBUG"] == "1" {
            NSLog("Aura: поймано в буфере [%@] %@", item.symbol, String(item.title.prefix(60)))
        }

        items.insert(item, at: 0)
        if items.count > settings.clipboardLimit {
            items.removeLast(items.count - settings.clipboardLimit)
        }

        if settings.persistClipboard {
            ClipboardStore.save(items, limit: settings.clipboardLimit)
        }

        // История ограничена лимитом и живёт для вставки; журнал хранит всё.
        if settings.archiveEverything {
            ClipboardArchive.append(item)
        }
    }

    /// Чинит текст, который положили в буфер как UTF-8, а система отдала
    /// разобранным в однобайтовой кодировке: «привет» превращается в «–њ—А–Є...».
    /// Такое присылают консольные утилиты и старые приложения.
    nonisolated static func repairEncoding(_ text: String) -> String {
        // Признак поломки — символы, которых в осмысленном тексте почти не бывает
        // подряд: они получаются из первых байтов кириллических пар UTF-8.
        let markers: Set<Character> = ["–", "—", "Ð", "Ñ", "Ã", "‚", "†", "¬"]
        guard text.contains(where: markers.contains) else { return text }

        // Байты UTF-8 могли быть разобраны как любая однобайтовая кодировка —
        // какая именно, зависит от системы отправителя, поэтому перебираем.
        let candidates: [String.Encoding] = [
            .init(rawValue: CFStringConvertEncodingToNSStringEncoding(
                CFStringEncoding(CFStringEncodings.macCyrillic.rawValue)
            )),
            .macOSRoman,
            .init(rawValue: CFStringConvertEncodingToNSStringEncoding(
                CFStringEncoding(CFStringEncodings.windowsCyrillic.rawValue)
            )),
            .isoLatin1,
        ]

        for encoding in candidates {
            guard let data = text.data(using: encoding),
                  let repaired = String(data: data, encoding: .utf8),
                  !repaired.isEmpty,
                  repaired.contains(where: { $0.isLetter })
            else { continue }
            return repaired
        }

        return text
    }

    /// В историю попадает уменьшенная копия: полноразмерные снимки экрана
    /// в сотне карточек — это сотни мегабайт памяти.
    private static func downscaled(_ image: NSImage, maxSide: CGFloat = 320) -> NSImage {
        let size = image.size
        guard size.width > maxSide || size.height > maxSide, size.width > 0, size.height > 0 else {
            return image
        }
        let scale = maxSide / max(size.width, size.height)
        let target = CGSize(width: size.width * scale, height: size.height * scale)

        let result = NSImage(size: target)
        result.lockFocus()
        NSGraphicsContext.current?.imageInterpolation = .medium
        image.draw(in: CGRect(origin: .zero, size: target))
        result.unlockFocus()
        return result
    }

    private func readKind(from pasteboard: NSPasteboard) -> ClipboardItem.Kind? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL], !urls.isEmpty {
            return .files(urls)
        }

        if let image = NSImage(pasteboard: pasteboard) {
            return .image(Self.downscaled(image))
        }

        guard let string = pasteboard.string(forType: .string), !string.isEmpty else {
            return nil
        }

        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)

        if let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto"].contains(scheme) {
            return .link(url)
        }

        if let color = NSColor(hex: trimmed) {
            return .color(color)
        }

        return .text(Self.repairEncoding(string))
    }
}

extension NSColor {
    /// Разбирает `#RGB`, `#RRGGBB` и `#RRGGBBAA`.
    convenience init?(hex: String) {
        var value = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        guard value.hasPrefix("#") else { return nil }
        value.removeFirst()

        if value.count == 3 {
            value = value.map { "\($0)\($0)" }.joined()
        }
        guard value.count == 6 || value.count == 8,
              let number = UInt64(value, radix: 16) else { return nil }

        let hasAlpha = value.count == 8
        let shift = hasAlpha ? 8 : 0
        let red = CGFloat((number >> (16 + shift)) & 0xFF) / 255
        let green = CGFloat((number >> (8 + shift)) & 0xFF) / 255
        let blue = CGFloat((number >> shift) & 0xFF) / 255
        let alpha = hasAlpha ? CGFloat(number & 0xFF) / 255 : 1

        self.init(srgbRed: red, green: green, blue: blue, alpha: alpha)
    }
}
